# Generated by Django 4.2.5 on 2023-09-10 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_bag_description_alter_item_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pack",
            name="bag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="packs",
                to="core.bag",
            ),
        ),
    ]
